### ISSUE TITLE
Migrate V1 to V2 in Tag 1.0.0b1 prerelease

### ISSUE THREAD

**Issue by ghost** [brooklyn-data/dbt_artifacts#146]
Hello @NiallRees 

loving what you have done with the beta version. Just one small question. I tried to migrate from V1 to V2 with the beta prerelease version installed and all the migration macros weren't available. 

Was this intentionally? Or maybe I just didn't read your release note not thoroughly...

Regards
FoxMulder

**Comment by NiallRees** [comment]
Hi @foxmulder4223 - the naming is a little confusing here so want to make sure I've understood.

In pre 1.0.0, there were two Snowflake upload mechanisms, a 'v1' and a 'v2'. Are you saying you're trying to switch from using the v1 upload mechanism to v2? If so, neither of those are available in the beta prerelease due to a complete redesign of the package.

**Comment by ghost** [comment]
Hey @NiallRees 

yeah you understood correctly. 
Well and that explains a lot. Thanks for the clarification. Much appreciated!

**Comment by NiallRees** [comment]
No worries!
