### ISSUE TITLE
ENV property empty which means stg_dbt__run_results_env_keys and related tables do not populate

### ISSUE THREAD

**Issue by ElliottWilson** [brooklyn-data/dbt_artifacts#17]
Hey thanks so much for doing this it has really helped me track our dbt run times. 

In the `run_results.json` artefact, I see that the env property is null:
![image](https://user-images.githubusercontent.com/32582638/114892937-96ea3300-9de3-11eb-8dc1-6399bad8078c.png)

This means that stg_dbt__run_results_env_keys is not being populated because the sql is looking for a env.key field. Is there anyway we can populate this field so I can use all the models. I am running dbt on the cloud. CTE below which references this field: 

![image](https://user-images.githubusercontent.com/32582638/114892846-82a63600-9de3-11eb-8ce2-4d6997d7c6a9.png)

Is the env variable a variable that I should be setting or an argument I should be passing in?

**Comment by kgpayne** [comment]
Hey @ElliottWilson 👋 Thanks for checking out `dbt_artifacts`!

I am not sure I understand what is missing in downstream tables? The env_vars above are [optional](https://github.com/tailsdotcom/dbt_artifacts/blob/main/models/incremental/fct_dbt__run_results.sql#L36). They are from your run environment, and can be injected into your artefacts by prefixing env vars with `DBT_ENV_CUSTOM_ENV_`, as per [the docs](https://docs.getdbt.com/reference/artifacts/dbt-artifacts#common-metadata). For most folks I would expect them to be blank, and if you are running on dbt Cloud custom env vars are not currently supported at all.

Any chance you are missing data in `fct_dbt__critical_path`? We are tracking an issue for dbt Cloud users uploading artefacts with the `run-operation upload_artifacts` macro. I created an issue for it just now #19 🙂 The root cause is mismatched `invocation_id`'s caused by `run-operation` overwriting `manifest.json` before uploading 🤦‍♂️

**Comment by NiallRees** [comment]
Hey @ElliottWilson - is this still an issue you're facing?
