### ISSUE TITLE
Slack notifications

### ISSUE THREAD

**Issue by Triangulum9r** [brooklyn-data/dbt_artifacts#204]
Is there a way to add slack notifications on model failure similar to DBT cloud?

**Comment by jaypeedevlin** [comment]
Hey Julius,

I might have misunderstood your question, and if so let me know, but I'll do my best to answer.

If you use dbt Cloud, any failures from the posthook or downstream models should trigger a notification that you've setup.  If you're not using dbt Cloud you'd have to work out how to configure notifications within your orchestration platform.

Because notifications belong at the orchestration level, providing them is out of scope for this package.
