### ISSUE TITLE
Column names and types

### ISSUE THREAD

**Issue by artem110101** [brooklyn-data/dbt_artifacts#241]
Hi!

I can't find column metadata in the result data.
Is there any specific reason why this package doesn't have it ? Are you open to having it ? I can give a try to contributing it.

Thanks

**Comment by VDFaller** [comment]
**Edit** Seems like what I'm asking for is to change the `tests.name` field to use double underscores to delimit between package__test__table.  

I think this is similar to my ask.  I would love it if I could join these pieces of information without having to parse out of the node.  All of this is so that I can rollup/filter the failures for users the tables that they care about.  I'm going to talk about tests but this might work for other tables as well. 

* endpoint_type (source, seed, model)
  * could parse this out of `stg_dbt_tests.depends_on_nodes` pretty easily
* test_name
  * if node_id or  `stg_dbt_tests.name` used double underscores to delimiter I might be able to do parse this out easier. 
    * like instead of dbt_expectations_expect_compound_columns_to_be_unique_table_name__item_1__item_2
    * it was dbt_expectations__expect_compound_columns_to_be_unique__table_name__item_1__item_2
* table_name
  * null if no table
  * where the test is defined
  * double underscore solution might work here too
* column_name
  * null if no column
* arguments
  * could just be a json ( {"column_list":["item_1", "item_2"]} ) in my example
  * double underscore solution might work here too

*Edit 2* realizing that this probably comes from dbt-core

**Comment by glsdown** [comment]
Hi @artemboiko1 . I'm afraid I'm not 100% sure what you are referencing here. Please could you provide an example?

@VDFaller I'm not sure if this is what you are looking for, but in v2.4.0 we have added a new field in the `sources` tables, `all_results` which contains a JSON blob of the results object used, which you can use in your own analysis:

- exposures
- models
- seeds
- snapshots
- sources
- tests

This contains all detail provided by dbt core directly.

**Comment by VDFaller** [comment]
I'll check it out today.

**Comment by glsdown** [comment]
It looks like this has now been resolved, so I'm going to close the issue. Please feel free to reopen it if that is not the case.
