### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by jgilfillan** [brooklyn-data/dbt_artifacts#273]
There's been no commit activity in nearly 3 months despite several pending pull requests and a number of issues raised. Would be good to hear from one of the maintainers if this is just a temporary pause and if not, when commit activity is expected to resume.

**Comment by glsdown** [comment]
Hello @jgilfillan , sorry for the delay in getting back to you. The project isn't dead, it's just been temporarily paused whilst other things were being worked on. We are going to put a concerted effort into addressing the open PRs and issues, but any contributions to achieve this would also be welcomed. 

Thanks for reaching out, and sorry that it's been a while since the project has seen some ❤️
