### ISSUE TITLE
[Feature]: populate column rows_affected for Databricks / Spark

### ISSUE THREAD

**Issue by mvdwielen** [brooklyn-data/dbt_artifacts#332]
Hi,

I noticed that the column rows_affected is not populated for Databricks, is this because this adapter is not returning this information causing this column to be empty? Do you happen to know where I should request this feature in such dbt artifacts can use this?

Kind regards,

Marc

**Comment by jared-rimmer** [comment]
Hi @mvdwielen 

Thanks for opening the issue. 

You're correct. In the dbt [BigQuery](https://github.com/search?q=repo%3Adbt-labs%2Fdbt-bigquery%20rows_affected&type=code) and [Snowflake](https://github.com/dbt-labs/dbt-snowflake/blob/3e8a49f50c947b228eaccc7c686d9aaa9459fb43/dbt/adapters/snowflake/connections.py#L379) adapters `rows_affected` comes from the adapter response class.

This isn't present in the Databricks dbt adapter and would need to be added in there in order to be pulled in

**Comment by mvdwielen** [comment]
@jared-rimmer clear, thx for quick reply
