### ISSUE TITLE
[Bug] Had an issue upgrading dbt-artifact to 2.6.0

### ISSUE THREAD

**Issue by ajonesINQ** [brooklyn-data/dbt_artifacts#397]
## Overview

Tried upgrading dbt-artifacts from 2.4 to 2.6. the upgrade was successful, however after our job ran the artifact was not able to be uploaded to bigquery as the query was too long.
## Expected behaviour

We would expect the artifact data to be uploaded to bigquery and the job not to fail

## Screenshots
<img width="944" alt="job_fail_for_issue" src="https://github.com/brooklyn-data/dbt_artifacts/assets/102986551/d3d90ddd-2951-4719-ae42-f2c6469c80b1">

## Environment

Results of running `dbt --version`:
dbt=1.6.5

```sh
# Add the results here
```

Please paste the contents of your `packages.yml` file here:

```yml
packages:
  ------------------------------------------------------------
  Invoke dbt Command
------------------------------------------------------------
dbt deps

05:00:49  Running with dbt=1.6.5
05:00:49  Installing dbt-labs/dbt_utils
05:00:49  Installed from version 1.1.1
05:00:49  Installing calogica/dbt_expectations
05:00:50  Installed from version 0.10.0
05:00:50  Installing dbt-labs/codegen
05:00:50  Installed from version 0.11.0
05:00:50  Installing data-mie/dbt_profiler
05:00:50  Installed from version 0.8.1
05:00:50  Installing dbt-labs/dbt_project_evaluator
```

**Comment by glsdown** [comment]
Hello. As noted in #369 we added a new feature in 2.6.0 which will hopefully help here. In a previous release, we added an additional `all_results` column which contained a [JSON object of all results](https://github.com/brooklyn-data/dbt_artifacts#creating-custom-marts-tables) for people to be able to do their own analysis on. However, this increased the query size dramatically, which is why these issues started arising.

In the latest release, I've added a variable that will stop this behaviour to reduce the query size. Please can you try adding the following as a variable in your `dbt_project.yml` file and see if that resolves it?

```yml
vars:
  dbt_artifacts_exclude_all_results: true
```

**Comment by jared-rimmer** [comment]
@ajonesINQ are you still seeing this issue after implementing the above?

**Comment by data-modeler** [comment]
I came here with the same problem and adding the variable solved the problem for me.  Thanks!

**Comment by ajonesINQ** [comment]
So sorry thought I commented on this ages ago the above did resolve my issue. thank you
